name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:    
      - main
      - 'release/**'

env:
  TERRAFORM_VERSION: 1.7.1

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    - name: Test terraform code
      run: |
        make test